/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideRouteImport } from './routes/aide'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as MilieuRouteImport } from './routes/milieu'
import { Route as SanteRouteImport } from './routes/sante'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TerritoiresRouteImport } from './routes/territoires'
import { Route as TerritoiresIndexRouteImport } from './routes/territoires.index'
import { Route as TerritoiresSlugRouteImport } from './routes/territoires.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const MilieuRoute = MilieuRouteImport.update({
  id: '/milieu',
  path: '/milieu',
  getParentRoute: () => rootRouteImport,
} as any)
const SanteRoute = SanteRouteImport.update({
  id: '/sante',
  path: '/sante',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoiresRoute = TerritoiresRouteImport.update({
  id: '/territoires',
  path: '/territoires',
  getParentRoute: () => rootRouteImport,
} as any)
const TerritoiresIndexRoute = TerritoiresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerritoiresRoute,
} as any)
const TerritoiresSlugRoute = TerritoiresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TerritoiresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/evolution': typeof EvolutionRoute
  '/milieu': typeof MilieuRoute
  '/sante': typeof SanteRoute
  '/sources': typeof SourcesRoute
  '/territoires': typeof TerritoiresRouteWithChildren
  '/territoires/$slug': typeof TerritoiresSlugRoute
  '/territoires/': typeof TerritoiresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/evolution': typeof EvolutionRoute
  '/milieu': typeof MilieuRoute
  '/sante': typeof SanteRoute
  '/sources': typeof SourcesRoute
  '/territoires/$slug': typeof TerritoiresSlugRoute
  '/territoires': typeof TerritoiresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/evolution': typeof EvolutionRoute
  '/milieu': typeof MilieuRoute
  '/sante': typeof SanteRoute
  '/sources': typeof SourcesRoute
  '/territoires': typeof TerritoiresRouteWithChildren
  '/territoires/$slug': typeof TerritoiresSlugRoute
  '/territoires/': typeof TerritoiresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/evolution'
    | '/milieu'
    | '/sante'
    | '/sources'
    | '/territoires'
    | '/territoires/$slug'
    | '/territoires/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/evolution'
    | '/milieu'
    | '/sante'
    | '/sources'
    | '/territoires/$slug'
    | '/territoires'
  id:
    | '__root__'
    | '/'
    | '/aide'
    | '/evolution'
    | '/milieu'
    | '/sante'
    | '/sources'
    | '/territoires'
    | '/territoires/$slug'
    | '/territoires/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AideRoute: typeof AideRoute
  EvolutionRoute: typeof EvolutionRoute
  MilieuRoute: typeof MilieuRoute
  SanteRoute: typeof SanteRoute
  SourcesRoute: typeof SourcesRoute
  TerritoiresRoute: typeof TerritoiresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milieu': {
      id: '/milieu'
      path: '/milieu'
      fullPath: '/milieu'
      preLoaderRoute: typeof MilieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sante': {
      id: '/sante'
      path: '/sante'
      fullPath: '/sante'
      preLoaderRoute: typeof SanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territoires': {
      id: '/territoires'
      path: '/territoires'
      fullPath: '/territoires'
      preLoaderRoute: typeof TerritoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/territoires/': {
      id: '/territoires/'
      path: '/'
      fullPath: '/territoires/'
      preLoaderRoute: typeof TerritoiresIndexRouteImport
      parentRoute: typeof TerritoiresRoute
    }
    '/territoires/$slug': {
      id: '/territoires/$slug'
      path: '/$slug'
      fullPath: '/territoires/$slug'
      preLoaderRoute: typeof TerritoiresSlugRouteImport
      parentRoute: typeof TerritoiresRoute
    }
  }
}

interface TerritoiresRouteChildren {
  TerritoiresSlugRoute: typeof TerritoiresSlugRoute
  TerritoiresIndexRoute: typeof TerritoiresIndexRoute
}

const TerritoiresRouteChildren: TerritoiresRouteChildren = {
  TerritoiresSlugRoute: TerritoiresSlugRoute,
  TerritoiresIndexRoute: TerritoiresIndexRoute,
}

const TerritoiresRouteWithChildren = TerritoiresRoute._addFileChildren(
  TerritoiresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AideRoute: AideRoute,
  EvolutionRoute: EvolutionRoute,
  MilieuRoute: MilieuRoute,
  SanteRoute: SanteRoute,
  SourcesRoute: SourcesRoute,
  TerritoiresRoute: TerritoiresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
